apiVersion: v1
kind: Service
metadata:
  name: tessrax
spec:
  type: {{ .Values.service.type }}
  selector:
    app: tessrax
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
